### ISSUE TITLE
Improper detection of 64-bit system?

### ISSUE THREAD

**Issue by 1n5aN1aC** [SKCraft/Launcher#104]
So I'm not sure if this is the real problem, but I've run across a system where I get the following error:

    UnsatisfiedLinkError: Z:\Windows.Documents\My Documents\13-thirtyseven Launcher\temp\extract\1447351145484\lwjgl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform

But yet the launcher works perfectly fine on other 64-bit systems, so I'm not sure what is amiss here.  FYI, this is with the bootstrapper, build works perfectly on all other 64-bit systems I have used.  Here is the full log:

    Unable to launch
    java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
		at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    Caused by: java.lang.UnsatisfiedLinkError: Z:\Windows.Documents\My Documents\13-thirtyseven Launcher\temp\extract\1447351145484\lwjgl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
		at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_60]
		at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_60]
		at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_60]
		at java.lang.Runtime.loadLibrary0(UnknException in thread "main" own Source) ~[?:1.8.0_60]
		at java.lang.System.loadLibrary(Unknown Source) ~[?:1.8.0_60]
		at org.lwjgl.Sys$1.run(Sys.java:73) ~[lwjgl-2.9.1.jar:?]
		at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
		at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.1.jar:?]
		at org.lwjgl.Sys.loadLibrary(Sys.java:95) ~[lwjgl-2.9.1.jar:?]
		at org.lwjgl.Sys.<clinit>(Sys.java:112) ~[lwjgl-2.9.1.jar:?]
		at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2671) ~[bao.class:?]
		at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
		... 6 more

**Comment by sk89q** [comment]
How many different versions of Java are installed on that system?

**Comment by 1n5aN1aC** [comment]
Alright, so I figured out this was some sort of permissions error.  Some file or files got extracted with restrictive permissions (due to drive settings) which caused this error.

Fixed it by setting permissions on the entire launcher files directory (in windows' documents) recursively.

So it's not a 'problem' per see, but I wonder if additional checking for something like this should, or even can be implemented.

**Comment by sk89q** [comment]
Did the permissions only allow writing and not reading? Realistically I don't think many people (if any) have previously had this problem so I don't think a check is really necessary. The real issue here is that Java doesn't print out a useful error message.

**Comment by 1n5aN1aC** [comment]
Would the dll's need execution privileges?

Because I think that the problem is probably that the permission on that drive doesn't allow execution of executables written there without first allowing that via changing the file's permissions.

I would have thought a program loading a dll wouldn't need execute permissions, but... I'm not very familiar with how dll loading and such works on windows.
