### ISSUE TITLE
1.8.9 Pack error when attempting to download

### ISSUE THREAD

**Issue by Thorinori** [SKCraft/Launcher#136]
So I have a bunch of 1.7.10 packs up and running, and wanted to make a test 1.8.9 pack, and whenever I attempt to download it to the launcher from my website I get:
`To report this error, please provide:

java.io.IOException: 1 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
I am unsure of if this error is with forge, with the launcher, with java, or with minecraft/mojang

**Comment by dj3520** [comment]
Check your url.txt files. The launcher can't download a file.

**Comment by Nincodedo** [comment]
Make sure your launcher has this PR included. It should have fixed this issue. https://github.com/SKCraft/Launcher/pull/122

**Comment by Thorinori** [comment]
I redownloaded the master to make sure I had all the latest PRs, and recompiled my launcher. Still getting an error:
```
java.io.IOException: 1 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

Not sure which url.txt file you are talking about dj3520

**Comment by Nincodedo** [comment]
I haven't used the creator tools so I'm not sure what that error is exactly. In your upload folder do you have anything in libraries\jline\jline\2.13?

**Comment by Thorinori** [comment]
Yeah, I do have it in my folder apparently. That log was from when it compiles to make sure it runs :s

**Comment by Thorinori** [comment]
I think I may have fixed it, I forgot to reupload before checking

**Comment by Thorinori** [comment]
I apparently was wrong, same errors in testing

**Comment by sk89q** [comment]
Are you using the creator tools download or the one that you compiled yourself (along with the launcher)?

The creator tools download is currently outdated. Use the creator tools from the creator-tools/build/libs folder if you aren't already. However, you also need to apply the simple change listed in #122 if you haven't already.

When analyzing the log file, you can see:

* **[info] Downloading library jline:jline:2.13 from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz...**
* [info] Could not get file from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz: Did not get expected response code, got 404 for http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz
* **[info] Downloading library jline:jline:2.13 from https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar...**
* [info] Could not get file from https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar: Did not get expected response code, got 403 for https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar
* **[info] Downloading library jline:jline:2.13 from https://central.maven.org/maven2/jline/jline/2.13/jline-2.13.jar...**
* [info] Could not get file from https://central.maven.org/maven2/jline/jline/2.13/jline-2.13.jar: java.security.cert.CertificateException: No subject alternative DNS name matching central.maven.org found.
* **[info] Downloading library jline:jline:2.13 from http://maven.apache.org/jline/jline/2.13/jline-2.13.jar...**
* [info] Could not get file from http://maven.apache.org/jline/jline/2.13/jline-2.13.jar: Did not get expected response code, got 404 for http://maven.apache.org/jline/jline/2.13/jline-2.13.jar
* **[warning] !! Failed to download the library jline:jline:2.13 -- this means your copy of the libraries will lack this file**

It's hitting four different URLs to try to find the file:

1. http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz...
2. https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar
3. https://central.maven.org/maven2/jline/jline/2.13/jline-2.13.jar
4. http://maven.apache.org/jline/jline/2.13/jline-2.13.jar

...and it's not in any of these places. It *used* to be at URL #3 but maven.org moved everything over to repo1.maven.org. The purpose of #122 is that it changes the maven_repos.json file to reflect the URL change.

**Comment by Thorinori** [comment]
I have been using the creator tools that I built with the launcher. It seems the issue was a combination of having to update the launcher and at least one of my mods was corrupted. After redownloading every mod the test function worked just fine. I am in the process of uploading the pack and testing through the launcher. Thank you all for the help!

**Comment by jtrent238** [comment]
It don't work with 1.8.9 for SME reason

**Comment by James137137** [comment]
1.8.9 works for me

**Comment by jtrent238** [comment]
[](url)

**Comment by jtrent238** [comment]
[                                      ](https://github.com/SKCraft/Launcher/issues/136#issuecomment-185008845)

**Comment by Plusgames** [comment]
How do i updated the URL in the Modpack Creator

**Comment by dj3520** [comment]
For mods the url is in .jar.url.txt files. For anything else, which would
be about the launcher, you'd have to recompile.

**Comment by MJRamon** [comment]
creator-tools\build\libs\creator-tools-2.0.2-SNAPSHOT-all.jar works for 1.9

Thanks

**Comment by Keridos** [comment]
For me compiling with the updated maven.repos fixed the creator tools but my fancy launcher still has the problem with downloading jline. The maven.repos file in the jar has the correct url though.
