### ISSUE TITLE
User encountering strange error

### ISSUE THREAD

**Issue by Entoarox** [SKCraft/Launcher#142]
One of my users is encountering a rather strange error whenever they try to use the bootstrapper to download the launcher:

```
java.net.SocketException: Address family not supported by protocol family: connect
 at java.net.DualStackPlainSocketImpl.connect0(Native Method)
 at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
 at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
 at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
 at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
 at java.net.PlainSocketImpl.connect(Unknown Source)
 at java.net.SocksSocketImpl.connect(Unknown Source)
 at java.net.Socket.connect(Unknown Source)
 at java.net.Socket.connect(Unknown Source)
 at sun.net.NetworkClient.doConnect(Unknown Source)
 at sun.net.www.http.HttpClient.openServer(Unknown Source)
 at sun.net.www.http.HttpClient.openServer(Unknown Source)
 at sun.net.www.http.HttpClient.<init>(Unknown Source)
 at sun.net.www.http.HttpClient.New(Unknown Source)
 at sun.net.www.http.HttpClient.New(Unknown Source)
 at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
 at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
 at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
 at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
 at com.skcraft.launcher.bootstrap.HttpRequest.execute(HttpRequest.java:115)
 at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:73)
 at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
 at java.lang.Thread.run(Unknown Source)
```

Now, my knowledge of java is unfortunately very basic, so this is quite a bit beyond my ability to understand myself, let alone what is actually causing the issue here.

**Comment by ajthemacboy** [comment]
My knowledge of both Java and webservers are basic too, but here are some things that might help:

- Check if you can `telnet` to the host
- Check that the firewall isn't blocking the connection, and make sure that port 80 is forwarded
- Probably unrelated, but make sure the launcher is in the correct .jar.pack format
- Try the launcher with `-Djava.net.preferIPv4Stack=true`, (maybe) this is related to IPV4/6 issues..?

**Comment by sk89q** [comment]
What's the status of this issue?

**Comment by Entoarox** [comment]
Issue found, the user in question had to force their java to use IPv4 in order for the connection to work.

**Comment by sk89q** [comment]
Let me know if this is still an issue.
