### ISSUE TITLE
[Resolved] files could not be downloaded

### ISSUE THREAD

**Issue by elwooha6** [SKCraft/Launcher#151]
This happens as the launcher is downloading the minecraft client.

To report this error, please provide:

java.io.IOException: 2 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by elwooha6** [comment]
Not entirely sure what fixed it but I did update maven and now it works.

**Comment by jtrent238** [comment]
I Get it to alot it just cant get the files

```
`To report this error, please provide:

java.io.IOException: 1 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
```
