### ISSUE TITLE
Mods are corrupted

### ISSUE THREAD

**Issue by FedorAronov** [SKCraft/Launcher#167]
Launcher downloads all files, but Forge can't load mods:
Example:
Zip file fastcraft.jar failed to read properly, it will be ignored
java.util.zip.ZipException: invalid END header (bad central directory offset)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_111]
	at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:41) [JarDiscoverer.class:?]
	at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by sk89q** [comment]
This is typically because of your web host.

**Comment by FedorAronov** [comment]
Why mods are corrupted, but all other files are downloaded correctly?

**Comment by sk89q** [comment]
What other files? Text files?

**Comment by FedorAronov** [comment]
Yes :-) Configs!

**Comment by sk89q** [comment]
Another frequent reason is uploading files over FTP in text or automatic
mode, which makes subtle changes to the content of files that is not
noticeable in text files but completely breaks non-text files.

**Comment by FedorAronov** [comment]
Thanks!
