### ISSUE TITLE
Other users getting error on launch. (bootstrap/fancy)

### ISSUE THREAD

**Issue by 100photos** [SKCraft/Launcher#185]
So I made a modpack, and one of the players (out of two since it just released and its just one "for fun") said they couldnt play the pack. I asked them for errors and they gave me this image: <img src="https://cdn.discordapp.com/attachments/282150194076844032/285924808192032769/unknown.png"> I tried my best to reproduce this but to no avail. It works for me, even in portable mode. I couldnt find the answer elsewhere so I decided to post here. Does anyone here know the probable cause?

**Comment by sk89q** [comment]
What versions of Forge have you tried? Give me the filenames that you have tried of the Forge installer.

**Comment by 100photos** [comment]
The only one I've tried so far is forge-1.7.10-10.13.4.1614-1.7.10-installer.jar since thats what most of the mods use and the server uses. Does it only work with certain versions?

**Comment by 100photos** [comment]
Another person got 
```
To report this error, please provide:

java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
```
mid-download. Idk whats wrong with it thats making so many people getting different errors

**Comment by 100photos** [comment]
Another person got:
```
To report this error, please provide:

java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
```
Why is everyone getting different errors?
Do you need the jar?

**Comment by WyvernTrc** [comment]
@100photos they are getting the last error because the launcher can't fetch the version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.json tried to get the file manually but it don't work too.

**Comment by 100photos** [comment]
Minecraft is down lol 
https://help.mojang.com/
http://downdetector.com/status/minecraft
http://www.isitdownrightnow.com/minecraft.net.html
https://status.aws.amazon.com/
Rip

**Comment by 100photos** [comment]
What do these errors mean, he got them with most of the mods
```
[22:29:31] [main/ERROR] [FML]: Unable to read the jar file AoA-2.4.B.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by dj3520** [comment]
`java.net.ConnectException: Connection timed out: connect`
A network connection died.
`java.util.zip.ZipException: error in opening zip file`
Corrupt file/invalid jar
