### ISSUE TITLE
Building pack leads to crash:

### ISSUE THREAD

**Issue by squirrelkiller** [SKCraft/Launcher#187]
```
To report this error, please provide:

java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at com.skcraft.launcher.builder.ClientFileCollector.onFile(ClientFileCollector.java:76)
	at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.java:73)
	at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.java:68)
	at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.java:43)
	at com.skcraft.launcher.builder.PackageBuilder.addFiles(PackageBuilder.java:114)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

This happens whenever I try to build a pack, the mod this happens on seems somewhat random.

**Comment by sk89q** [comment]
Closing. Re-open if you still have the problem.
