### ISSUE TITLE
Can not Construct Instance of Library/Action

### ISSUE THREAD

**Issue by berkinay2** [SKCraft/Launcher#190]
To report this error, please provide:

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.skcraft.launcher.model.minecraft.Library$Action, problem: No enum constant com.skcraft.launcher.model.minecraft.Library.Action.DİSALLOW
 at [Source: java.io.StringReader@62c71bac; line: 300, column: 21] (through reference chain: com.skcraft.launcher.model.minecraft.VersionManifest["libraries"]->com.skcraft.launcher.model.minecraft.Library["rules"]->com.skcraft.launcher.model.minecraft.Rule["action"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:170)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:710)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer$FactoryBasedDeserializer.deserialize(EnumDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2986)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.update.Updater.readVersionManifest(Updater.java:118)
	at com.skcraft.launcher.update.Updater.update(Updater.java:146)
	at com.skcraft.launcher.update.Updater.call(Updater.java:92)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.skcraft.launcher.model.minecraft.Library.Action.DİSALLOW
	at java.lang.Enum.valueOf(Unknown Source)
	at com.skcraft.launcher.model.minecraft.Library$Action.valueOf(Library.java:182)
	at com.skcraft.launcher.model.minecraft.Library$Action.fromJson(Library.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer$FactoryBasedDeserializer.deserialize(EnumDeserializer.java:162)
	... 29 more

**Comment by sk89q** [comment]
Closing. Re-open if you still have the problem.
