### ISSUE TITLE
Running Minecraft Vanilla issue. Have done a few repairs through installation manager, but it freezes on the mojang screen.

### ISSUE THREAD

**Issue by Game024Over** [SKCraft/Launcher#198]
[19:23:41] [Client thread/INFO]: Setting user: Game024Over
[19:23:44] [Client thread/INFO]: LWJGL Version: 2.9.4
[19:23:45] [Client thread/INFO]: Reloading ResourceManager: Default
[19:23:46] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:23:46] [Thread-3/INFO]: Initializing LWJGL OpenAL
[19:23:46] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:23:47] [Thread-3/INFO]: OpenAL initialized.

This is the last log

**Comment by Nincodedo** [comment]
Can you post the whole log? This doesn't really tell much.

**Comment by Game024Over** [comment]
*** MagicMinecraftLauncher 1.3.4 ***
  LCP: ;bin/jinput.jar;bin/lwjgl.jar;bin/lwjgl_util.jar;C:\Users\King\Desktop\1.12\1.12.jar
  McVersion: 1.12
  MainClass: net.minecraft.client.Minecraft
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at magic.launcher.Launcher.main(SourceFile:188)



This is what the Magic Launcher says

**Comment by Game024Over** [comment]
Where do I find the entire log?



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Game024Over** [comment]
‹       }ÐÁNƒ@à{“¾Ã5Ñ¥T4éÞŒ¦M
JR=¶2Àše—ƒ¤>½@ÑÆC½Ï÷Ï?“øéræï y0-„*õÖ/Ëh'!Ffmshj$	+UâlDŸHÓI2Úàœ
ßžV!¼"ÕÚY	s±Á‰Ýžc4N¥ýÒ
Ö®¡w|VVåýþGÌTcør×…Ä®±)„zOŠvé·>+:ö¯`˜‹5c)„ø›±\ßü¸µÕ¬•Ñ_½=ÞUhïÃÿÙÅ¶Àq|¯ípƒËF) –Ž t„ mæ¨TÜýå
jD(˜+éymÛ
Ó~äF8Ê/§“o8ú«ðŸ  


If this helps

**Comment by Game024Over** [comment]
These are the only logs Im seeing, located in logs folder
,

**Comment by wizjany** [comment]
this isn't magic launcher...?
