### ISSUE TITLE
need guidance(need advice how to setup with bitbucket)

### ISSUE THREAD

**Issue by SDUBZ** [SKCraft/Launcher#203]
cant seem to find out any info on how to put launcher and get it to grab from bitbucket

any advice/help would be very helpful

**Comment by SDUBZ** [comment]
all i keep running into is this error when im trying to set it up myself
To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@50b5fdc8; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:141)
	... 5 more

**Comment by jtrent238** [comment]
What link do you have in the `launcher.properties` file

**Comment by SDUBZ** [comment]
for packages i was using the following

not sure if i was using correct format due to not many guides on how to do this launcher with bitbucket

https://bitbucket.org/sdubz/launcher.bitbucket.io/src/b451f4cfd8c5ec0e7b7d542bfcd1808674af5422/packages.json

https://bitbucket.org/sdubz/launcher.bitbucket.io/src/b451f4cfd8c5ec0e7b7d542bfcd1808674af5422/news.html

https://bitbucket.org/sdubz/launcher.bitbucket.io/src/b451f4cfd8c5ec0e7b7d542bfcd1808674af5422/latest.json

**Comment by wizjany** [comment]
you need to use the raw urls like this
https://bitbucket.org/sdubz/launcher.bitbucket.io/raw/b451f4cfd8c5ec0e7b7d542bfcd1808674af5422/packages.json
note how you just get a pure json file instead of a web page

**Comment by SDUBZ** [comment]
so instead src use raw and it will get read by launcher basically and thanks guys :)
