### ISSUE TITLE
launcher not reading latest.json

### ISSUE THREAD

**Issue by SDUBZ** [SKCraft/Launcher#204]
just wondering if anyone could give advice for http://sdubzcraft.epizy.com/latest.json why it would not be ready a launcher 

please help not the best at understanding why this launcher would or wouldnt read these files from a url

yes ive changed build in the gradle.build
and changed version number in latest json

any help would be greatly appreciated

**Comment by sk89q** [comment]
try putting http:// in the url

**Comment by SDUBZ** [comment]
i have got the http:// in the url space

**Comment by spannerman79** [comment]
```
{
    "version": "0.0.7",
    "url": "sdubzcraft.epizy.com/launcher.jar.pack"
}
```
No you don't - look at line 3

**Comment by SDUBZ** [comment]
oh there sorry :/
i will try
and see if it fixes it

**Comment by SDUBZ** [comment]
made those changes and still its giving me To report this error, provide:

java.io.IOException: Update URL did not return a valid result
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:91)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

**Comment by SDUBZ** [comment]
heres my properties of boot strap: 
http://puu.sh/xzXOJ/5227b30a7d.properties

and launcher.properties:

http://puu.sh/xzXRs/fced604cee.properties

if it helps any

**Comment by sk89q** [comment]
Let me know if this is still an issue.
