### ISSUE TITLE
1.12 crashes on macOS

### ISSUE THREAD

**Issue by Proplex** [SKCraft/Launcher#205]
Hey there, loving this launcher. Interesting problem with macOS, and it's due to a missing library. I've created an empty 1.12.2 pack for users who which to play basic vanilla and it works great on Windows--but it seems on macOS it's crashing because of a missing library required for the new narration functionality. Through the Mojang client, it works fine. 

Here's the client crash summary:
```
Caused by: java.lang.ClassNotFoundException: ca.weblite.objc.NSObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```
Although it works fine through the Mojang launcher (for me), some quick Googling of this issue shows that other people have experienced it: https://bugs.mojang.com/browse/MC-118506

It seems like an edge case since the report is rare and Mojang hasn't addressed it at all. 

I notice that the Launcher is fetching the .jar from the enumerated libraries list:
```
[info] Fetching ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar from [https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar, http://togame.ipwnage.com/launcher/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar]
```

But it seems like a futile effort since it crashes.

I've tried building the vanilla pack with the java-objc-bridge-1.0.0.jar in `./src/libraries/ca/weblite/java-objc-bridge/1.0.0` but that doesn't seem to help either.

Any ideas? I've hit a wall here. 
Here's the full Launcher log (with download output + launch crash): https://ipwnage.com/stuff/vanilla_crash.txt

**Comment by Tberdy** [comment]
Hey ! I have currently the same problem. I made some tests like adding the library in the folder, then add it in the manifest file, but it keeps failing... I think we have to dig in the code to see where the librairies are downloaded, to add the missing one.

**Comment by jwulf** [comment]
I have the same problem. 

I've tried copying  `java-objc-bridge-1.0.0.jar` to `.modpacks/staging/launcher/libraries/ca/weblite/java-objc-bridge/1.0.0`

Same result - crashes.

**Comment by panwolfram** [comment]
I've got the same error, with 1.12.1. I couldn't figure out how to connect this library to my modpack...

**Comment by gailingmic** [comment]
yes this error still exists funnily enough it also tries to download some libraries wich 404 
```[information] Downloading library net.minecraft:launchwrapper:1.12 from https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar...
[information] Downloading library org.ow2.asm:asm-all:5.2 from http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar.pack.xz...
[information] Could not get file from http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar.pack.xz: Did not get expected response code, got 404 for http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar.pack.xz
[information] Downloading library org.ow2.asm:asm-all:5.2 from https://libraries.minecraft.net/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar...
[information] Could not get file from https://libraries.minecraft.net/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
[information] Downloading library org.ow2.asm:asm-all:5.2 from https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar...
[information] Downloading library jline:jline:2.13 from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz...
[information] Could not get file from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz: Did not get expected response code, got 404 for http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.pack.xz
[information] Downloading library jline:jline:2.13 from https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar...
[information] Could not get file from https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar: Did not get expected response code, got 404 for https://libraries.minecraft.net/jline/jline/2.13/jline-2.13.jar```

seems like exactly this is the problem we're experiencing

**Comment by DaMatrix** [comment]
Can confirm, a number of my users are unable to launch because of this.

**Comment by jkroepke** [comment]
I can't launch it, too. Same error. Maybe it just works on the original launcher.

Maybe a libPath is missing?

**Comment by jkroepke** [comment]
I resolved this issues by using the fixes from forge and modify the distributed versionManifest from mojang.

See: https://gist.github.com/jkroepke/bea657959a625c50297ceb7797df452c

Maybe this isn't straight forward, but it just works.

**Comment by panwolfram** [comment]
@jkroepke Could you please tell me how to apply this fix to `creator-tools`?

**Comment by jkroepke** [comment]
Do have not any knowledge about Java coding. Sorry.

**Comment by panwolfram** [comment]
Great! That worked perfectly!

**Comment by gailingmic** [comment]
Awesome to hear that its the error i pointed to! Maybe someone can fix it in java now :-) the forge commit should explain it good enough (would do it myself but im only good in c++)

**Comment by panwolfram** [comment]
Could anyone fix it?

**Comment by sk89q** [comment]
Is still an issue I should look into?

**Comment by panwolfram** [comment]
Yes, it's still an issue. I can't launch literally any modpack because of it.

**Comment by gailingmic** [comment]
Yes its still an issue! The forge guys had the exact same error too and managed to fix it! All you have to do is to not search for the mac natives as tbeyre packaged with the game already.
