### ISSUE TITLE
I'm getting this error and no packs are visible to the left

### ISSUE THREAD

**Issue by Aezwen** [SKCraft/Launcher#206]
Opening launcher-4.3-SNAPSHOT-all from a fresh install.
To report this error, please provide:

java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.skcraft.launcher.util.HttpRequest.returnContent(HttpRequest.java:214)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:140)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

Error goes away if I click ok twice but there are no packs to the left. Error returns when clicking check for updates.
Am I missing something? http://void-band.com/minecraft/Modpack/packages.json seems to point to the right files.

Also launcher-fancy nothing happens if I open launcher-fancy-4.3-SNAPSHOT-all.jar

**Comment by i9hdkill** [comment]
https://github.com/SKCraft/Launcher/issues/207

**Comment by sk89q** [comment]
Fixed
