### ISSUE TITLE
JNI error

### ISSUE THREAD

**Issue by TheHeroBilly** [SKCraft/Launcher#208]
Built this from just the code provided and any time I try to launch the jars I get this error. Nothing really specific. Any ideas on how I can fix it?

**Comment by TheHeroBilly** [comment]
Using latest Java (8) and latest JDK

**Comment by wizjany** [comment]
might help if you actually posted the error

**Comment by TheHeroBilly** [comment]
I don't get one. It just says a JNI error has occurred

**Comment by TheHeroBilly** [comment]
Console doesn't help, I ran it and it doesn't give an error other than the pop up from before

**Comment by thommy101** [comment]
How did you package it? I know eclipse has some options to include libraries. This sounds like there are some missing libraries to me.

**Comment by TheHeroBilly** [comment]
I ran the Gradle bat file included here

**Comment by sk89q** [comment]
Which jars exhibit the problem? Both the launcher and the bootstrap?

**Comment by TheHeroBilly** [comment]
All of them, the modpack creator as well

**Comment by wizjany** [comment]
it would probably help if you could include os info, java version info, gradle log, etc.

**Comment by rouing** [comment]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/TypeReference
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.type.TypeReference
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

**Comment by sk89q** [comment]
Let me know if this is still an issue.
