### ISSUE TITLE
Error when downloading modpack.

### ISSUE THREAD

**Issue by cedmen1** [SKCraft/Launcher#211]
Hello guys when im trying to download the modpack its saying this : 

To report this error, please provide:

java.io.IOException: 2 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sk89q** [comment]
Open the console before starting download (it's via the options dialog) and it will show the actual files.

**Comment by cedmen1** [comment]
Its saying the same thing ...
