### ISSUE TITLE
1.13 snapshots not downloading

### ISSUE THREAD

**Issue by BLCKBRRY** [SKCraft/Launcher#220]
Hello, i've recently downloaded SKlauncher, i can play all the Minecraft versions up to 1.12.2 but when i try playing in the 1.13 snapshots it does not load, the game actually opens but before the "Mojang" screen appears the game closes itself and gives this output in the launcher:

[14:45:55] [Client thread/INFO]: Setting user: LiteCraft
[14:46:01] [Client thread/WARN]: Skipping bad option: lastServer:
[14:46:01] [Client thread/ERROR]: Something went wrong upgrading!
java.lang.NumberFormatException: For input string: "48:CONTROL"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_151]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_151]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_151]
	at wl.a(SourceFile:154) ~[17w47b.jar:?]
	at ur.b(SourceFile:55) ~[17w47b.jar:?]
	at ur.a(SourceFile:40) [17w47b.jar:?]
	at bmk.a(SourceFile:1004) [17w47b.jar:?]
	at bmk.a(SourceFile:776) [17w47b.jar:?]
	at bmk.<init>(SourceFile:373) [17w47b.jar:?]
	at bmh.an(SourceFile:400) [17w47b.jar:?]
	at bmh.a(SourceFile:361) [17w47b.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:134) [17w47b.jar:?]
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.playerlist:key.tab
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.advancements:38
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.5:6
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.6:7
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.7:8
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.8:9
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.1:2
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.2:3
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.3:4
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.4:5
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.sprint:29
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.forward:17
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.drop:16
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.back:31
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.attack:-100
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.use:-99
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.saveToolbarActivator:46
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.smoothCamera:0
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.right:32
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.jump:57
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.sneak:42
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.spectatorOutlines:0
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.left:30
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.command:53
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.screenshot:60
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.hotbar.9:10
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.togglePerspective:63
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.chat:20
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.inventory:18
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.fullscreen:87
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.loadToolbarActivator:45
[14:46:01] [Client thread/WARN]: Skipping bad option: key_key.swapHands:33
[14:46:01] [Client thread/INFO]: LWJGL Version: 3.1.2 build 29
[14:46:07] [Client thread/INFO]: Reloading ResourceManager: Default, ModdedFaithful 1.12.2-rv1.zip, Faithful 1.12.2-rv4.zip
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fee50424cd, pid=7172, tid=0x000000000000100c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [lwjgl.dll+0x124cd]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Tuco\AppData\Roaming\.minecraft\hs_err_pid7172.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[LWJGL] A function that is not available in the current context was called. The JVM will abort execution. Inspect the crash log to find the responsible Java frames.
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

what can i do to fix this?

**Comment by sk89q** [comment]
Let me know if this is still an issue.
