### ISSUE TITLE
How to configure Dropbox

### ISSUE THREAD

**Issue by lborruto** [SKCraft/Launcher#229]
Hi guys,
How I can configure Dropbox ? I can get the `packages.json` from it but I cant download anything else.

```
To report this error, please provide:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "packages" (class com.skcraft.launcher.model.modpack.Manifest), not marked as ignorable (12 known properties: "gameVersion", "versionManifest", "objectsLocation", "minimumVersion", "name", "librariesLocation", "tasks", "launch", "title", "version", "features", "baseUrl"])
 at [Source: java.io.StringReader@7b1eab6b; line: 3, column: 17] (through reference chain: com.skcraft.launcher.model.modpack.Manifest["packages"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:671)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:761)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1275)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2986)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:90)
	at com.skcraft.launcher.update.Updater.update(Updater.java:141)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Thanks !

**Comment by sk89q** [comment]
Unfortunately I am not sure you can anymore because they disabled website hosting even for older account holders.
