### ISSUE TITLE
The list of modpacks could not be downloaded

### ISSUE THREAD

**Issue by alexkar598** [SKCraft/Launcher#241]
```
To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@1b3d7844; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:141)
	... 5 more

```

This shows up in a dialog twice on startup and twice when checking for updates.
config(note:i only set it to be a txt to upload it):
[launcher.properties.txt](https://github.com/SKCraft/Launcher/files/2184331/launcher.properties.txt)

**Comment by sk89q** [comment]
http://techhavenlaunche.ihostfull.com/packages.json?key=%s

doesn't even load for me

**Comment by alexkar598** [comment]
Weird,i tried on 2 devices and it loads

**Comment by spannerman79** [comment]
> Weird,i tried on 2 devices and it loads

```
curl -v http://techhavenlaunche.ihostfull.com/packages.json?key=%s&i=1
[1] 1521
*   Trying 185.27.134.135...
* connect to 185.27.134.135 port 80 failed: Connection timed out
* Failed to connect to techhavenlaunche.ihostfull.com port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to techhavenlaunche.ihostfull.com port 80: Connection timed out
```
"Trying" on another device =! how java http library works.

Conclusion: Stop using "free" hosting as it just doesn't work.

**Comment by deltachase** [comment]
If you want, I can get it hosted on my launcher for free. Just message me on Discord and we can talk :)
