### ISSUE TITLE
Error when testing modpack (modpack creator)

### ISSUE THREAD

**Issue by iKingTom** [SKCraft/Launcher#251]
i get this error every time i try to test or build a modpack with or without mods or loaders

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:175)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

please help i've tried finding a fix and i can't

**Comment by SDUBZ** [comment]
same here To report this error, please provide:

java.io.IOException: 2 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hedgehog1029** [comment]
Loader errors should be fixed in master now.
