### ISSUE TITLE
a list of modpacks can not be downloaded

### ISSUE THREAD

**Issue by quindao** [SKCraft/Launcher#254]
how do I fix this 
java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Did not get expected response code, got 521 for http://update.skcraft.com/template/packages.json?key=
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:139)
	... 5 more

**Comment by spannerman79** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare

Not an issue with the launcher - fix your website.

**Comment by Tomoli75** [comment]
Not his website, it's the skcraft website.
