### ISSUE TITLE
Java Error on Run

### ISSUE THREAD

**Issue by CharlyZhu** [SKCraft/Launcher#267]
Minecraft Version: 1.13.2;
Manifest: http://eu.mcdiguo.com/launcher_data/launch-game.json
When I am trying to run the program, the downloading part and the extraction part seemed fine, but when it tries to launch game, this error pops up.
Thanks in advance for any help/support!!!

java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again

**Comment by jiudejlx** [comment]
Hello, We have the exact same problem!!! I wonder if you have solved the problem, if so, how? Thank you in advance.

**Comment by hedgehog1029** [comment]
Possibly related to previously broken 1.13 support; should work with the latest version.
