### ISSUE TITLE
Mods not downloading

### ISSUE THREAD

**Issue by tacogerbil** [SKCraft/Launcher#269]
Thank your your time,
I have a personal modpack and have used sklauncher for quite a while.  The first few times I was using a "hostmonster" web server I was paying for, using ftp to upload.  Recently I got a synology NAS and started using it's web server to host.  I use a Mac and transfer my files over using the finder.  My Mac is able to build successfully and then is also able to use the launcher to log in and download the modpack updates then play just fine.  It removes old mods and installs the new ones just fine.  On my sons windows machine it also downloads updates just fine.  My nephew has a Mac and I can't get his to download the mods successfully.. they are not complete/corrupted downloads.  Not a firewall or anything as everyone is in my house and has unfettered access.  SKLauncher downloads the other minecraft files just fine.  You know something goes wrong when the launcher game window tells you that you are missing such and such mods.   This is a sample of the error for EVERY mod in the modpack..
ANY help would be greatly appreciated.
[11:01:46] [main/INFO] [FML]: Java is Java HotSpot™sing 64-Bit Server VM, version 1.8.0_144, running on Mac OS X:x86_64:10.14.1, installed at /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
[11:01:46] [main/ERROR] [FML]: Unable to read the jar file ProjectRed-1.12.2-4.9.1.92-Base.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_144]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:200) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:169) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:97) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:139) [forge-1.12.2-14.23.5.2770.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by sk89q** [comment]
If you open up one of the jar files in a test editor, what's inside?

**Comment by tacogerbil** [comment]
I'm sorry, "test editor"?  Can I use a text editor?  I tried unzipping them one as I've don with actual jars and it was corrupt.  They were all about 33k in size (including huge mods like pixelmon).

**Comment by tacogerbil** [comment]
Question.. Does this launcher have issues with APFS?  I notice it's the only distinguishing factor when we use the launchers..  My nephew is using APFS in his macbook while we're using MacOS Extended (Journaled)..  
Some interesting facts..  IF I remove the Instance and launch the launcher it will download ALL the mods just fine.. Once it's there it will sporadically update SOME mods and not others.. or the file partially.  I have to manually delete all his mods and copy them over from my mod repo at that point.
Seems like other things like "Custom Main Menu" folders and "Enchiridion" folders I have in the config folder are transferring over just fine.

**Comment by sk89q** [comment]
Sorry I meant text editor. It will be gibberish but the kind of gibberish is important. 

I'm not aware of any reason why the launcher would be incompatible. It doesn't do any special operations with the file system.
