### ISSUE TITLE
Launcher Update for Java 8 support?

### ISSUE THREAD

**Issue by SirWilli** [SKCraft/Launcher#27]
hey @sk89q,

when will you update the launcher for Java 8 support? 
I get so many reports from players that they can't launch the modpacks because of this error:
```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.remove(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Process ended with code: 0
```

**Comment by sk89q** [comment]
Closing due to age.
