### ISSUE TITLE
The jar objc bridge still didn't load into the classpath

### ISSUE THREAD

**Issue by AzureZhen** [SKCraft/Launcher#276]
I am using 1.12.2 Forge 2768 and when someone on OSX tries to use the launcher they get this error. 
`Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/NarratorOSX
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:22)
	at net.minecraft.client.gui.chat.NarratorChatListener.<init>(SourceFile:15)
	at net.minecraft.client.gui.chat.NarratorChatListener.<clinit>(SourceFile:14)
	at net.minecraft.client.gui.GuiIngame.<init>(GuiIngame.java:148)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:101)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.NarratorOSX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: ca/weblite/objc/NSObject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 16 more
Caused by: java.lang.ClassNotFoundException: ca.weblite.objc.NSObject
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more`

**Comment by spannerman79** [comment]
Dupe https://github.com/SKCraft/Launcher/issues/234

Hint: See up the top left that says "Search or jump to"? Could have typed in `NarratorOSX` then hit enter

**Comment by Pichuminer** [comment]
Oof.
