### ISSUE TITLE
[1.12.2] Forge

### ISSUE THREAD

**Issue by Honeycake** [SKCraft/Launcher#284]
Hello,

on 1.12.2 I get following Error on startup (Test)
```
The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1
```
Folders are setup like this:
```
|-> modpack.json
|- [loaders]
|-> forge-1.12.2-14.23.4.2766-installer.jar
|- [src]
|-> [config]
|-> [mods]
|-> [resourcepacks]
```

**Comment by spannerman79** [comment]
Drop down java versions, to say 8.

**Comment by spannerman79** [comment]
In fact a simple search would have given you that answer https://is.gd/FH9MXB

**Comment by Honeycake** [comment]
I tried it now with a clean setup of the Modpack Cretor.
And I'm using Java 8....
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
```
It only crashes if I put the forger-installer into the loaders folder

**Comment by spannerman79** [comment]
Works correctly https://pastebin.com/1Txsa06C
```
D:\MODPACK_TEST\FORGE_TEST
│   modpack.json
│
├───loaders
│       forge-1.12.2-14.23.5.2815-installer.jar
│
└───src
    ├───config
    ├───mods
    └───resourcepacks
```

**Comment by spannerman79** [comment]
And checked with the version of forge you had listed
https://pastebin.com/SY6m86cS
```
D:\MODPACK_TEST\FORGE_TEST
│   modpack.json
│
├───loaders
│       forge-1.12.2-14.23.4.2766-installer.jar
│
└───src
    ├───config
    ├───mods
    └───resourcepacks
```

Issue is on your end. Not a modpack creator tool issue.

**Comment by hedgehog1029** [comment]
Happens when running the game with Java 9+, use the launcher's custom java path option.
