### ISSUE TITLE
3 files could not be downloaded

### ISSUE THREAD

**Issue by Kore-Development** [SKCraft/Launcher#287]
```
java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
[Click here for log](https://pastebin.com/2PbYGNWq)

**Comment by spannerman79** [comment]
`[info] Enumerating libraries to download...
[info] Added library source: http://launcher.pqtato.pw/libraries/`

**Comment by evanlegamer** [comment]
Hi, Did you understand the problem?

**Comment by hedgehog1029** [comment]
Should be fixed with the latest version.
