### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by langeover** [SKCraft/Launcher#298]
Hi i have some problem on my launcher when i start my modpack is going to crash but my website is ok, if you have a idee ? i give my log at crash : https://pastebin.com/dL8rFx97
I sorry if my english is bad i'm french but thanks for your help

**Comment by spannerman79** [comment]
`Failed to download https://langeover.ovh/LaunchOver/upload/objects/99/cd/99cd3865a1a4bfea3f378afbd850eb8baacd183d
java.io.IOException: Did not get expected response code, got 403 for https://langeover.ovh/LaunchOver/upload/objects/99/cd/99cd3865a1a4bfea3f378afbd850eb8baacd183d`
https://httpstatuses.com/403

Not a launcher issue - fix your web server.

**Comment by langeover** [comment]
oky and the launcher give me that error : To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)




i've forgot to tell it in my last message

**Comment by langeover** [comment]
hi, i have check my ftp all is good (perm files problem ?) on my website but the launcher download all a file of the modpack and in the end he don't want to download 3 files (194 files ok and 3 files failed for example) but all files is in the even folder than good file.
if you have a idee i can test ?
thanks you
