### ISSUE TITLE
Can not Construct Instance of com.skcraft.model.minecraft.Library$Action, 

### ISSUE THREAD

**Issue by NeutronRasee** [SKCraft/Launcher#301]
To report this error, please provide:

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.skcraft.launcher.model.minecraft.Library$Action, problem: No enum constant com.skcraft.launcher.model.minecraft.Library.Action.DİSALLOW
 at [Source: java.io.StringReader@407053c1; line: 158, column: 9] (through reference chain: com.skcraft.launcher.model.modpack.Manifest["versionManifest"]->com.skcraft.launcher.model.minecraft.VersionManifest["libraries"]->com.skcraft.launcher.model.minecraft.Library["rules"]->com.skcraft.launcher.model.minecraft.Rule["action"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:170)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:710)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer$FactoryBasedDeserializer.deserialize(EnumDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2986)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:90)
	at com.skcraft.launcher.update.Updater.update(Updater.java:141)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.skcraft.launcher.model.minecraft.Library.Action.DİSALLOW
	at java.lang.Enum.valueOf(Unknown Source)
	at com.skcraft.launcher.model.minecraft.Library$Action.valueOf(Library.java:182)
	at com.skcraft.launcher.model.minecraft.Library$Action.fromJson(Library.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer$FactoryBasedDeserializer.deserialize(EnumDeserializer.java:162)
	... 33 more

**Comment by NeutronRasee** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10965683/57988004-89aa5980-7a91-11e9-9d4f-da1842777257.png)
Reinstalled jdk, java and launcher but still same error.

**Comment by spannerman79** [comment]
`gradlew -v` output?

**Comment by NeutronRasee** [comment]
This problem caused by my system language. If you get this error, change your system language to English.

**Comment by spannerman79** [comment]
If you have changed/self tagged this issue as solved why re-open?

**Comment by spannerman79** [comment]
> This problem caused by my system language. If you get this error, change your system language to English.

The main dev/s code in english - you **cannot** expect them to change to your language.

It would be foolish to expect for me to go over to (example) Japan and expect **everyone** to speak and write in english.

Personally - I don't think this is a launcher issue but a codepage issue to do with your system and outside the scope of this issue tracker.

**Comment by berkayoz** [comment]
The problem is caused by the system language as @NeutronRasee said before. Changing the display language as stated solves the problem but not really. The problem occurs on runtime when Jackson tries to serialize / deserialize values. Because the user is using a foreign display language (in our case Turkish) the serialization / deserialization throws an exception when lower case 'i' gets converted to upper case 'İ' in Turkish language instead of 'I. As shown in the error 

> com.skcraft.launcher.model.minecraft.Library.Action.DİSALLOW

"disallow" gets converted to enum "DİSALLOW" which is not  recognizable. The culprit is the fromJson function in com.skcraft.launcher.model.minecraft.Library.Action. 

`   
private enum Action {
        ALLOW,
        DISALLOW;

        @JsonCreator
        public static Action fromJson(String text) {
            return valueOf(text.toUpperCase());
        }

        @JsonValue
        public String toJson() {
            return name().toLowerCase();
        }
    }
`
The "text.toUpperCase()" call converts the "disallow" to "DİSALLOW" for Turkish language which causes the exception. We can solve this problem by using a Locale as shown below.
`
    private enum Action {
        ALLOW,
        DISALLOW;

        @JsonCreator
        public static Action fromJson(String text) {
            return valueOf(text.toUpperCase(new Locale("en", "US")));
        }

        @JsonValue
        public String toJson() {
            return name().toLowerCase(new Locale("en", "US"));
        }
    }
`

**Comment by spannerman79** [comment]
> Because the user is using a foreign display language (in our case Turkish)

That is a gradle issue for you @berkayoz and https://github.com/gradle/gradle/issues/1506 would apply.
