### ISSUE TITLE
The launcher is not working

### ISSUE THREAD

**Issue by ShonP40** [SKCraft/Launcher#305]
`java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@4cf8a3e7; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:141)
	... 5 more`

**Comment by spannerman79** [comment]
Duplicate of #241 (plus many others)

**Comment by ShonP40** [comment]
The website is working.
I already tried Dropbox ,Mega and FTP hosting and I am getting the same error.

**Comment by spannerman79** [comment]
> I already tried Dropbox ,Mega and FTP hosting

The http "lib" that handles file transfers can only handle a *direct* URL link. Not something that uses javascript like the first two.  And [FTP =! HTTP](https://techdifferences.com/difference-between-http-and-ftp.html).

You **cannot** use "free" hosting.

Read the wiki - all this is already answered there and also in the issue that i references which you obviously didn't read fully.

**Comment by ShonP40** [comment]
I ended up hosting it on GitHub and now it works.
