### ISSUE TITLE
The launcher won't launch my modpack

### ISSUE THREAD

**Issue by ShonP40** [SKCraft/Launcher#306]
```The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher
Step 1

http://bfy.tw/OLxW

**Not a Launcher issue**

**Comment by ShonP40** [comment]
Turns out I had Java 11 installed...
