### ISSUE TITLE
im really confused

### ISSUE THREAD

**Issue by darealHeroBrine** [SKCraft/Launcher#321]
im following the tut step by step and i get this error multiple times granted that the y are slightly different
1st test      https://pastebin.com/S6XU0bSh
2nd:       https://pastebin.com/BdxxsWMD
3rd:           https://pastebin.com/S6XU0bSh

**Comment by seeker2921** [comment]
All three of those past's have been deleted from pastebin??

**Comment by darealHeroBrine** [comment]
i do not know i can make new ones i didnt change any settings between then and now but basicly as soon as the game opens a second later it closes/crashes with exit code 1

**Comment by darealHeroBrine** [comment]
and i am unable to use pack200 it crashes with no exit code or anything to tell me how to fix it :( yay

**Comment by darealHeroBrine** [comment]
and this To report this error, provide:

java.net.UnknownHostException: update.skcraft.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.PlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at com.skcraft.launcher.bootstrap.HttpRequest.execute(HttpRequest.java:115)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:73)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by darealHeroBrine** [comment]
**https://pastebin.com/yH0Gg7Ya**

**Comment by spannerman79** [comment]
`java.io.IOException: MD5 not matching`

Not a launcher issue.

https://lmgtfy.com/?q=java.io.IOException%3A+MD5+not+matching+minecraft

**Comment by darealHeroBrine** [comment]
if i understand this right the issue is from optifine? i have it disabled? is it still in effect unless i remove it?

**Comment by seeker2921** [comment]
Yes, it still applys core code, even if you don't use any of its features.

**Comment by darealHeroBrine** [comment]
im getting this error from starting the launcher/modpack
To report this error, please provide:

java.io.IOException: 8 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by darealHeroBrine** [comment]
the recent issue is fixed (fix: re build the pack)

**Comment by darealHeroBrine** [comment]
bootstrapper error:
To report this error, provide:

java.io.IOException: Did not get expected response code, got 404 for http://www.thetnz.com/Client/Launcher/1.0-SNAPSHOT.jar.pack
	at com.skcraft.launcher.bootstrap.HttpRequest.expectResponseCode(HttpRequest.java:154)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:101)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by darealHeroBrine** [comment]
i also am having a bootstrapper issue and i cant open up the fancy launcher

**Comment by darealHeroBrine** [comment]
and pack 200 is not registered as a commnd
is there a diff program i could use to pack the jar?

**Comment by darealHeroBrine** [comment]
i sent the launcher-all.jar to a friend and i am getting this error
The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
    at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

**Comment by darealHeroBrine** [comment]
I feel like my issues i send is getting deleted

**Comment by darealHeroBrine** [comment]
i also want my launche to connect to 1.12 upto 1.14 servers how can i do that?

**Comment by SoulSen** [comment]
I'm getting the same error

**Comment by darealHeroBrine** [comment]
Here is my latest issue

[info] Fetching version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json...
[warning] Task failed
java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by StrayanDropbear** [comment]
> Here is my latest issue
> 
> [info] Fetching version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json...
> [warning] Task failed
> java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json
> at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
> at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
> at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
> at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
> at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
> at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.base/java.lang.Thread.run(Unknown Source)

Any version after 1.12.2 wont work unless you apply the patches in the pull requests tab. See #299

**Comment by darealHeroBrine** [comment]
now its not accepting the forge installers
ar enot working

**Comment by darealHeroBrine** [comment]
To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by darealHeroBrine** [comment]
To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)

**Comment by hedgehog1029** [comment]
Lots of random errors in this thread that have probably been fixed.
