### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by Basti032002** [SKCraft/Launcher#324]
As I want to start my project it says

`The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1
`

**Comment by spannerman79** [comment]
A quick search of previous issues would have shown exactly how to fix your issue.  Not only that you didn't even read the wiki.......

**Comment by Magi1053** [comment]
You are trying to run the launcher with the wrong version of java, probably java 11. 
Please downgrade to java 8.

**Comment by hedgehog1029** [comment]
Java 9+ should be supported now.
