### ISSUE TITLE
Launcher can't launch minecraft forge Still

### ISSUE THREAD

**Issue by castlerush** [SKCraft/Launcher#33]
Ok so i followed the wiki, i downloaded my version of minecraft and i ran forge and forge added like 11 libraries to the libraries folder, i moved the libraries folder over to the webhost, and i launcher and still get this error.

[13:47:31] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:47:31] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_67]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_67]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by sk89q** [comment]
Closing due to age.
