### ISSUE TITLE
Unable to create/build the modpacks/package

### ISSUE THREAD

**Issue by darealHeroBrine** [SKCraft/Launcher#333]
Here is my latest issue

[info] Fetching version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json...
[warning] Task failed
java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json
at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by spannerman79** [comment]
Duplicate of https://github.com/SKCraft/Launcher/issues/235

**Comment by darealHeroBrine** [comment]
Thank you for the fix i just couldnt find it sorry
