### ISSUE TITLE
error on pack build

### ISSUE THREAD

**Issue by darealHeroBrine** [SKCraft/Launcher#334]
To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:175)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by spannerman79** [comment]
Read the wiki....

**Comment by Heimdell** [comment]
I get NPE at
```
[info] --- Checking for mod loaders to install... ---
[info] Installing forge-1.12.2-14.23.5.2854-installer.jar...
[warning] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
```
The reason being first chained call produces `null`.

**Comment by darealHeroBrine** [comment]
info] --- Checking for mod loaders to install... ---
[info] Installing forge.jar...
[warning] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by darealHeroBrine** [comment]
To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
