### ISSUE TITLE
Error when launch modpack

### ISSUE THREAD

**Issue by craffolo** [SKCraft/Launcher#338]
Hi, I followed the guide and I think I done all, but when I open the launcher ( and seems to be all ok) and I click launch it show this error.

`com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: java.io.StringReader@3e00008e; line: 1, column: 2]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:461)
at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:90)
at com.skcraft.launcher.update.Updater.update(Updater.java:141)
at com.skcraft.launcher.update.Updater.call(Updater.java:95)
at com.skcraft.launcher.update.Updater.call(Updater.java:38)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`

**Comment by spannerman79** [comment]
Did you actually follow the guide? https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher

**Comment by craffolo** [comment]
Yes, step by step. You think I made some mistake?

**Comment by craffolo** [comment]
> Did you actually follow the guide? https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher

**Comment by craffolo** [comment]
sorry i closed by mistake

**Comment by craffolo** [comment]
> Did you actually follow the guide? https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher

I used dropbox for upload all the file. It can be a problem?

**Comment by spannerman79** [comment]
.... Read the wiki... https://github.com/SKCraft/Launcher/wiki/Website-Hosting 

Its there for a reason

**Comment by craffolo** [comment]
oh thanks i didn't seen it damn. I was trying aws cloud but i  don't understand where to start. If you can give some tips would be very great. Thanks again

**Comment by craffolo** [comment]
i think i understood. i have to use amazon s3 cloud service? right?

**Comment by spannerman79** [comment]
> i think i understood. i have to use amazon s3 cloud service? right?

This is now outside the scope of this issue tracker.  This issue tracker is to report issues with the launcher itself.  Its not a "help I need to setup a webserver" etc tracker.

**Comment by craffolo** [comment]
god

**Comment by craffolo** [comment]
i have done

**Comment by hedgehog1029** [comment]
Probably bad webserver configuration; error message indicates that it's returning HTML or XML rather than JSON. Check the wiki and open a discussion if you're still having problems.
