### ISSUE TITLE
error building modpack

### ISSUE THREAD

**Issue by Sandro12366** [SKCraft/Launcher#340]
``java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
``

**Comment by jakeau** [comment]
> `java.io.IOException: 3 file(s) could not be downloaded at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139) at com.skcraft.launcher.install.Installer.download(Installer.java:46) at com.skcraft.launcher.update.Updater.update(Updater.java:178) at com.skcraft.launcher.update.Updater.call(Updater.java:95) at com.skcraft.launcher.update.Updater.call(Updater.java:38) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) `

Any luck? I have the same issue

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/issues/235

**Comment by hedgehog1029** [comment]
Should be fixed.
