### ISSUE TITLE
1.14.4 forge installer error

### ISSUE THREAD

**Issue by H4Mm3r** [SKCraft/Launcher#341]
Hey all,

I could patch de launcher.properties to get it woring but the "Test" is failing on :

[infos] --- Checking for mod loaders to install... ---
[infos] Installing forge-1.14.4-28.2.0-installer.jar...
[avertissement] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I've read that forge had changed sicne 1.13, but does it means that SKCraft is not 1.14.4 compatible yet ?

Thanks by advance

**Comment by miiichael** [comment]
See #235. Unfortunately it seems skcraft is semi-abandoned, so probably your best option is to attempt to work out which of the many many forks best suits your needs.

**Comment by H4Mm3r** [comment]
Do you know about a 1.14.4 compatible one ? There is 348 fork and the first one I'm testing aren't...
Thanks by advance !

**Comment by miiichael** [comment]
See the issue I just linked to, specifically references a year ago to @mindw0rm's fork that (presumably) contains a fix for the issue. :stuck_out_tongue:

**Comment by H4Mm3r** [comment]
I saw. But my problem is not fixed by those forks. It's not about the mojang changes, it's about a forge's one. This an have the same https://github.com/SKCraft/Launcher/issues/339 but this is not a duplicate issue... I'll try to answer this thread. Thanks for the help.

**Comment by H4Mm3r** [comment]
SKCraft is looking for the https://github.com/MinecraftForge/Installer/blob/1.5/src/main/resources/install_profile.json file, wich disapeared between the 1.5 and the 2.0 Forge's version. Is it any solution to fix the new Forge installation process ?
