### ISSUE TITLE
I have an error with Pack200

### ISSUE THREAD

**Issue by LennyLouis** [SKCraft/Launcher#344]
Hi, i want to make a forge 1.12.2-14.23.5.2821 modpack with ~150 mods and when i test it in the modpack creator i got this error : (i try with Java jre1.8.0_251 and jdk1.8.0_251 )

[info] --- Downloading libraries... ---

[info] Downloading library com.typesafe.akka:akka-actor_2.11:2.3.3 from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz...

[warning] Task failed
java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:143)
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:69)
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:56)
	at org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(CompressorStreamFactory.java:237)
	at com.skcraft.launcher.builder.Compressor.createInputStream(Compressor.java:34)
	at com.skcraft.launcher.builder.PackageBuilder.downloadLibraries(PackageBuilder.java:261)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:394)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by spannerman79** [comment]
Read step 1 https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher

**Comment by LennyLouis** [comment]
When i use the jdk specify in this step and i launch build.bat i got the same error when testing my modpack : 

[info] --- Downloading libraries... ---
[info] Downloading library com.typesafe.akka:akka-actor_2.11:2.3.3 from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz...
[warning] Task failed
java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:143)
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:69)
	at org.apache.commons.compress.compressors.pack200.Pack200CompressorInputStream.<init>(Pack200CompressorInputStream.java:56)
	at org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(CompressorStreamFactory.java:237)
	at com.skcraft.launcher.builder.Compressor.createInputStream(Compressor.java:34)
	at com.skcraft.launcher.builder.PackageBuilder.downloadLibraries(PackageBuilder.java:261)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:394)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

**Comment by spannerman79** [comment]
Sigh.... **again** read the step I gave.  You didn't read it fully.

**Comment by LennyLouis** [comment]
Ok, so i followed the instructions, but the problem was with my computer, i had Java 14 installed and 
no matter how much I changed the JAVA_HOME, the version used by the programs was still Java 14. I had to uninstall all other versions of java to make it work. Thank for your help @spannerman79
