### ISSUE TITLE
1.15.2 Forge Error

### ISSUE THREAD

**Issue by seanld03** [SKCraft/Launcher#346]
When trying to build the pack I get this error.

[info] --- Checking for mod loaders to install... ---
[info] Installing forge-1.15.2-31.1.0-installer.jar...
[warning] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by zavar152** [comment]
In my opinion, SKCraft doesn't support the 1.15.2. I tried to create it but i got an error. It said that this verison couldn't be found on mojang dowload server. May be we need to look through the code to fix this.

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/issues/235

**Comment by JustPlayerDE** [comment]
The new forge installer versions are the reason because they changed how it works.
Example (1.12 but this is the same for other versions of minecraft): 
![image](https://user-images.githubusercontent.com/19864478/84540183-2242f580-acf5-11ea-9c2b-28c93625acbd.png)


in the case of 1.12 the version 14.23.5.2847 is the last working version for SKCraft (but you cannot test it anymore)

**Comment by Tokeli** [comment]
This isn't an issue with the changed URLs in the launcher.properties. The install_profile.json file for Forge has had its structure completely rearranged.
