### ISSUE TITLE
3 Files Missing

### ISSUE THREAD

**Issue by New-Phoenix** [SKCraft/Launcher#350]
Full error log: https://hastebin.com/gufaniqare.rb

It said:
To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I have tried hosting libraries on my website but it keeps resetting it in launcher.properties after I re-build it
changing it after I re-build it has no effect either
**MC 1.7.10. It isn't 1.12/1.13+.**

**Comment by CheesyBC** [comment]
I have the same issue, but Its 12 of them missing on 1.8.9 (https://github.com/SKCraft/Launcher/issues/352)

**Comment by CheesyBC** [comment]
Also look at https://github.com/SKCraft/Launcher/issues/348 they are having the same issue

**Comment by New-Phoenix** [comment]
> Also look at #348 they are having the same issue and it looks like its solved

Whatever, you can't sign into your account anyway (my other issue), so there is really no point in even trying to fix this issue, because if you do, you still can't play, since licence accounts don't work and offline accounts aren't supported.

**Comment by spannerman79** [comment]
Resolved - see https://github.com/SKCraft/Launcher/issues/235#issuecomment-750944382

**Comment by hedgehog1029** [comment]
There's a whole bunch of duplicate issues with a similar problem; I'm going to assume it's fixed in master.
