### ISSUE TITLE
Modpack wont start when I put forge 1.8.9 into /loaders

### ISSUE THREAD

**Issue by CheesyBC** [SKCraft/Launcher#352]
I keep getting this error, I have tried multiple version jars too.
-----------------
java.io.IOException: 12 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hedgehog1029** [comment]
Just tested this with the latest 1.8.9 Forge installer and seems to work; the launcher has been heavily updated recently so old problems should be fixed :)
