### ISSUE TITLE
Forge is starting as vanilla

### ISSUE THREAD

**Issue by KarmaConfigs** [SKCraft/Launcher#353]
This is what happens when I try to launch forge 1.16.1

```
[17:24:54.553] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Player, --version, 1.16.1, --gameDir, C:\Modpacks\.modpacks\staging\launcher\instances\BW-1.16.1\minecraft, --assetsDir, C:\Modpacks\.modpacks\staging\launcher\assets, --assetIndex, 1.16, --uuid, 00000000-0000-0000-0000-000000000000, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 854, --height, 480, --launchTarget, skcraft, --fml.forgeVersion, 32.0.98, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.160719] 
[17:24:54.557] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_51 by Oracle Corporation 
[17:24:54.742] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Modpacks/.modpacks/staging/launcher/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=UNKNOWN 
[17:24:54.755] [main/ERROR] [LaunchServiceHandler/MODLAUNCHER]: Cannot find launch target skcraft, unable to launch 
Exception in thread "main" java.lang.RuntimeException: Cannot find launch target
	at cpw.mods.modlauncher.LaunchServiceHandler.validateLaunchTarget(LaunchServiceHandler.java:87)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
```

Does anyone know what could I do? I know the problem is at --launchTarget, skcraft,

**Comment by KarmaConfigs** [comment]
Edit:

Changed --launchTarget to minecraft, and now the error is this one

```
[17:39:30.048] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Player, --version, 1.16.1, --gameDir, C:\Modpacks\.modpacks\staging\launcher\instances\BW-1.16.1\minecraft, --assetsDir, C:\Modpacks\.modpacks\staging\launcher\assets, --assetIndex, 1.16, --uuid, 00000000-0000-0000-0000-000000000000, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 854, --height, 480, --launchTarget, minecraft, --fml.forgeVersion, 32.0.98, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.160719] 
[17:39:30.052] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_51 by Oracle Corporation 
[17:39:30.239] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Modpacks/.modpacks/staging/launcher/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=UNKNOWN 
Exception in thread "main" java.lang.IllegalStateException: Missing minecraft.client.jar environment property. Update your launcher!
	at cpw.mods.modlauncher.DefaultLaunchHandlerService.configureTransformationClassLoader(DefaultLaunchHandlerService.java:42)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.configureTransformationClassLoaderBuilder(LaunchServiceHandlerDecorator.java:44)
	at cpw.mods.modlauncher.LaunchServiceHandler.identifyTransformationTargets(LaunchServiceHandler.java:79)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:78)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
```

**Comment by KarmaConfigs** [comment]
Edit:

Fixed, but now forge is just not loading, the launcher is loading a vanilla minecraft instance

**Comment by kalkafox** [comment]
The launchtarget should be set to `fmlclient`. I tried this on my own already, but it still errors:

```
[09:49:53.712] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Kalka, --version, 1.15.2, --gameDir, C:\Users\kalka\Documents\test\.\instances\Wolfpack Unity\minecraft, --assetsDir, C:\Users\kalka\Documents\test\.\assets, --assetIndex, 1.15, --uuid, [redacted], --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.36, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --width, 854, --height, 480] 
[09:49:53.715] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_261 by Oracle Corporation 
[09:49:53.797] [main/ERROR] [LaunchServiceHandler/MODLAUNCHER]: Cannot find launch target fmlclient, unable to launch 
Exception in thread "main" java.lang.RuntimeException: Cannot find launch target
	at cpw.mods.modlauncher.LaunchServiceHandler.validateLaunchTarget(LaunchServiceHandler.java:87)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```

**Comment by sylphio** [comment]
@KarmaConfigs  @kalkafox Hi, thank for your other CL.  Did you figure out a solution to launch 1.16.3?
