### ISSUE TITLE
Minecraft 1.13 +

### ISSUE THREAD

**Issue by cmspeedau** [SKCraft/Launcher#354]
https://github.com/ZekerZhayard/ForgeWrapper

I found this while on GitHub could it help sort out the 2 year problem of no Mc 1.13+

**Comment by bruwyvn** [comment]
Check out these pull requests https://github.com/SKCraft/Launcher/pull/270 https://github.com/SKCraft/Launcher/pull/271 https://github.com/SKCraft/Launcher/pull/272 and how to merge it into your fork, there's problems with some loaders' installation but I manage to get the nether update working.

**Comment by cmspeedau** [comment]
when i am tedting a 1.15.2 pack in the pack builder i am getting this error
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cmspeedau** [comment]
from that? [info] Installing forge-1.15.2-31.2.31-installer.jar... do i still use the install jar or have they changed it
