### ISSUE TITLE
Launcher cant download 3 Libraries for 1.7.10 vanilla

### ISSUE THREAD

**Issue by Irgendwer01** [SKCraft/Launcher#359]
error:
java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
from log:
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Failed to download http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
java.io.IOException: Did not get expected response code, got 404 for http://localhost:40479/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
        at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
        at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warnung] Task failed
java.io.IOException: 3 file(s) could not be downloaded
        at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
        at com.skcraft.launcher.install.Installer.download(Installer.java:46)
        at com.skcraft.launcher.update.Updater.update(Updater.java:178)
        at com.skcraft.launcher.update.Updater.call(Updater.java:95)
        at com.skcraft.launcher.update.Updater.call(Updater.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by DrTheodor** [comment]
same issue

**Comment by FulI-Name** [comment]
I can help you two if you guys need help!

**Comment by sylphio** [comment]
#372
