### ISSUE TITLE
1.7.10 Download errors

### ISSUE THREAD

**Issue by wolflord212312** [SKCraft/Launcher#361]
I am trying to launch it as a test
i am useing the latest version of liteloader and forge

java.io.IOException: 11 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by DrTheodor** [comment]
i have the same issue, but with 1.12.2

**Comment by FulI-Name** [comment]
I can help ya both if you two still need help!

**Comment by DrTheodor** [comment]
> I can help ya both if you two still need help!

Yes, I still have this problem

**Comment by FulI-Name** [comment]
> > I can help ya both if you two still need help!
> 
> Yes, I still have this problem

So you cant download files for Forge?
