### ISSUE TITLE
Errors with loaders

### ISSUE THREAD

**Issue by AceKiller250** [SKCraft/Launcher#366]
when I try to run a modpack with the test feature I get an error message like this:

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

How can I fix this?

**Comment by FulI-Name** [comment]
What loader is this ur trying to use?
