### ISSUE TITLE
[1.16.4] Modpack doesn't start

### ISSUE THREAD

**Issue by DrTheodor** [SKCraft/Launcher#371]
[info] --- Reading version manifest... ---
[info] Fetching version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.16.4/1.16.4.json...
[warning] Task failed
java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.16.4/1.16.4.json
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:168)
	at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:63)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sylphio** [comment]
#372
