### ISSUE TITLE
I got an error occurred while launching the modpack

### ISSUE THREAD

**Issue by Caboose298** [SKCraft/Launcher#386]
I got an error code when try to launch my modpack ""through the launcher in Launcher-master\launcher\build\libs for I was only trying to test it real quick"" and I only started using this platform the other day I think I just need a little of help. I think I got the Modpack compiled correctly and I don't know where else to go for help who knows I'm probably doing something wrong thanks for the help.

error::

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@3c890a90; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:494)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:92)
	at com.skcraft.launcher.update.Updater.update(Updater.java:165)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hedgehog1029** [comment]
sounds like your web server is returning an HTML error page - gonna convert this into a help discussion
