### ISSUE TITLE
Forge 1.6.4 error - not loading

### ISSUE THREAD

**Issue by brunyman** [SKCraft/Launcher#389]
Hi,

So I'm testing with Tekkit 1.6.4 modpack, it loads as vanilla.
Here is the error:

[info] --- Checking for mod loaders to install... ---
[info] Installing forge-1.6.4-9.11.1.965-installer.jar...
[warning] Failed to add the loader at E:\WORK\LauncherWorkspace\tekkit\loaders\forge-1.6.4-9.11.1.965-installer.jar
com.fasterxml.jackson.databind.JsonMappingException: N/A (through reference chain: com.skcraft.launcher.model.loader.profiles.LegacyInstallProfile["versionInfo"]->com.skcraft.launcher.model.loader.VersionInfo["libraries"]->com.skcraft.launcher.model.minecraft.Library["url"])
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:571)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:554)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:117)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2986)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.builder.loaders.OldForgeLoaderProcessor.process(OldForgeLoaderProcessor.java:41)
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:179)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:134)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:432)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
	at com.google.common.base.Splitter.splitToList(Splitter.java:416)
	at com.skcraft.launcher.model.minecraft.Library.mavenNameToPath(Library.java:213)
	at com.skcraft.launcher.model.minecraft.Library.setUrl(Library.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:115)
	... 26 more

**Comment by hedgehog1029** [comment]
sigh, looks like that Forge version has a library in the manifest where `name` comes after `url`, which mucks up the processing

**Comment by hedgehog1029** [comment]
this particular bug is fixed in 40fcfdf992990064ed16b57d5edf57efce5297a3

**Comment by hedgehog1029** [comment]
fair warning: forge 1.6.4 seems to only run under java 7, FML & launchwrapper interact badly in that version and it breaks instantly on java 8
