### ISSUE TITLE
Hosting and building issues.

### ISSUE THREAD

**Issue by AceKiller250** [SKCraft/Launcher#403]
I got my 1.12.2 pack to work and when I test in the GUI it works. After building the modpack and putting it on dropbox I keep getting  this notification: To report this error, please provide:

java.util.UnknownFormatConversionException: Conversion = 'P'
	at java.util.Formatter$FormatSpecifier.conversion(Unknown Source)
	at java.util.Formatter$FormatSpecifier.<init>(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at com.skcraft.launcher.Launcher.getPackagesURL(Launcher.java:352)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:134)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Im not sure what this means nor how to fix it. Can anyone help?

**Comment by hedgehog1029** [comment]
Not sure Dropbox is supported anymore - looks like you have a `%` character in your URL which the launcher is trying to parse (it expands the URL in order to allow for game keys). Though perhaps we need a better way to do this because % characters are quite common in URLs, being part of the escape sequences...

**Comment by AceKiller250** [comment]
> Not sure Dropbox is supported anymore - looks like you have a `%` character in your URL which the launcher is trying to parse (it expands the URL in order to allow for game keys). Though perhaps we need a better way to do this because % characters are quite common in URLs, being part of the escape sequences...

Looks like your right. Jus changed the link to it not having % in it and now I'm getting this: To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@585d0943; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:517)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:141)
	... 5 more

Do you have any idea how to host these files on my Minecraft server or is it not possible?

**Comment by hedgehog1029** [comment]
Depending on your Minecraft server host, they may provide web hosting (or shell access which would potentially allow for web hosting). If not, you can get web hosting for cheap - basic paid web hosts are only around $2/mo, or there are services like [InfinityFree](https://infinityfree.net/) which are free (though the quality of free hosting can vary).
