### ISSUE TITLE
Launcher fails to create instances folder with vanilla "modpacks"

### ISSUE THREAD

**Issue by Katelyn-SN** [SKCraft/Launcher#41]
```
To report this error, please provide:

java.io.FileNotFoundException: .\instances\Vanilla 1.8\manifest.json (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.saveContent(HttpRequest.java:495)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:84)
	at com.skcraft.launcher.update.Updater.update(Updater.java:138)
	at com.skcraft.launcher.update.Updater.call(Updater.java:92)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by sk89q** [comment]
Unsure if I fixed this already, but one way to fix this is to put a dummy file in the "modpack."

**Comment by ajthemacboy** [comment]
A user is reporting the same issue, I have no clue why.

Perhaps this is the same issue? https://github.com/oxguy3/craftboot/issues/3

**Comment by sk89q** [comment]
AFAIK this was fixed but I could be wrong.

What's your version of the launcher?

**Comment by codydbgt** [comment]
i have the same issue im using the latest commit

**Comment by jtrent238** [comment]
There May Be Something "Blocking" The Download Of mainfest.json. I Think That Is With My Sister Any Way With Some Of The Mods.

**Comment by codydbgt** [comment]
no i didn't program the bootstrap if you include the bootstrap it will use a specific location as the files specified in the bootstrap config

**Comment by ajthemacboy** [comment]
This is again happening for only one of my users, still no idea why.

**Comment by sk89q** [comment]
Maybe no permission to create folders? Check if any files or folders are created on the user's computer.
