### ISSUE TITLE
NOT WORKING 

### ISSUE THREAD

**Issue by MD211211** [SKCraft/Launcher#411]
This is the error message java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Did not get expected response code, got 503 for http://update.skcraft.com/template/packages.json?key=
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:210)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:139)
	... 5 more
Tell ne how to fix

**Comment by theswampire** [comment]
The 503 response code indicates a server misconfiguration but I see that you are using the default/placeholder settings to fetch the packages. Make sure to edit the launcher.properties file!

But still, I guess their server is not working properly🤔

**Comment by MD211211** [comment]
I did edit the propeties file and i edited it but i got this errror please fix

**Comment by theswampire** [comment]
I'd suggest taking a look here #406
It seems to be a similar problem

**Comment by hedgehog1029** [comment]
Gradle seems to have some trouble lately with uncaching resources (the similarity to #406 is correct) - I think the root project `clean` doesn't trigger a clean on all subprojects - that's something I can fix.

@MD211211 don't be rude & demanding, thanks.
