### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by MD211211** [SKCraft/Launcher#412]
Ummm i tried it again and got this code 
java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Did not get expected response code, got 503 for http://update.skcraft.com/template/packages.json?key=
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:210)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:139)
	... 5 more
Can you also fix this please?

**Comment by MD211211** [comment]
And when i  go to http://update.skcraft.com/template/packages.json?key= it says 503 error

**Comment by MD211211** [comment]
Yes i did edit the propeties file to my website and stuff BUT when i  run it i have same issue an dyes i did redowload the launcher maker

**Comment by MD211211** [comment]
Ok so I also just uploaded the files to my ftp and still error

**Comment by MD211211** [comment]
heres the file https://www.mediafire.com/folder/lu5k4cd7zkd24/My+client

**Comment by hedgehog1029** [comment]
Everything looks in order there. Are you using `build.bat` to build the launcher? The fact the template URL is persisting just shows me that the launcher hasn't been rebuilt properly.

**Comment by hedgehog1029** [comment]
You've changed the `launcher.properties` file but the URLs are still not valid, so you're gonna get a similar-looking error. You can't just shove a random URL in there, you need to actually point it at the correct files ([see this section on the wiki](https://github.com/SKCraft/Launcher/wiki/Initial-Steps#customizing-the-launcher)).

If the error message still mentions `update.skcraft.com` then the launcher hasn't been rebuilt properly.

**Comment by MD211211** [comment]
Oh that is my website but I don’t now my webftp link on my builder it doesn’t say it anywhere

**Comment by MD211211** [comment]
Will it work if I use wix file share then link the properties to the file share instead of using ftp because I don’t know how to use them

**Comment by hedgehog1029** [comment]
Yeah I doubt a website builder lets you have direct FTP access.

If the uploaded files can be linked directly (i.e. in raw form, no HTML cruft) then that should work OK.

**Comment by MD211211** [comment]
Yesyesyyesyeysyeysy thx for the answer

**Comment by MD211211** [comment]
All the website builders do not ACCEPT the file type of the upload files any recommended one

**Comment by MD211211** [comment]
Ok i did connect to my website now andi got this To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@376337e5; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:549)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:141)
	... 5 more
Heres the website link https://maxerlauncher.wixsite.com/my-site/file-share The password is Maxer21

**Comment by MD211211** [comment]
OH YA i know why it cant connect becuase its PRIVATE

**Comment by MD211211** [comment]
That didnt work

**Comment by hedgehog1029** [comment]
You want the URL of the packages.json file (https://wix.anyfileapp.net/dl?id=553246736447566b583139426f554273717a50517567474659437956727043746b77674d5742436b5543357933377a4e6277724578664e753747665661495064514f3133644139622b505136776c6134436a4e6b6f773d3d)

**Comment by MD211211** [comment]
how did you know that

**Comment by MD211211** [comment]
UH "o report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Did not get expected response code, got 403 for https://wix.anyfileapp.net/dl?id=553246736447566b583139426f554273717a50517567474659437956727043746b77674d5742436b5543357933377a4e6277724578664e753747665661495064514f3133644139622b505136776c6134436a4e6b6f773d3d
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:210)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:139)
	... 5 more" said error

**Comment by hedgehog1029** [comment]
Not sure why you're getting a 403.

You might be better off using one of the services [listed on the wiki](https://github.com/SKCraft/Launcher/wiki/Website-Hosting).

**Comment by MD211211** [comment]
Will GitHub pages work and also how to upload files to github pages

**Comment by MD211211** [comment]
Or connect a web ftp

**Comment by hedgehog1029** [comment]
Go read the docs: https://docs.github.com/en/github/working-with-github-pages

This should've been converted to a discussion long ago, doing that now.
