### ISSUE TITLE
Something went wrong, httpdownloader....

### ISSUE THREAD

**Issue by i-eat-burgers** [SKCraft/Launcher#424]
java.io.IOException: Something went wrong
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:134)
	at com.skcraft.launcher.install.Installer.download(Installer.java:50)
	at com.skcraft.launcher.update.Updater.update(Updater.java:203)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No connection has been made
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:132)
	... 8 more
Caused by: java.lang.IllegalArgumentException: No connection has been made
	at com.skcraft.launcher.util.HttpRequest.getResponseCode(HttpRequest.java:243)
	at com.skcraft.launcher.util.HttpRequest.isSuccessCode(HttpRequest.java:255)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:272)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	... 4 more

I have the latest SKCraft Launcher files. The forge is 1.16.5 recommended.

**Comment by hedgehog1029** [comment]
can you paste ([inside a code block, ideally](https://i.witch.gq/YnL28E1z.png)) the error that is logged to the console right before this happens. It'll be right after the words `Failed to download`. I suspect you have a bad URL that is preventing the connection from ever being created.

I will fix the error that you've given, but it's actually hiding another error that was just caught. So even when I fix it you'll get another error.

**Comment by i-eat-burgers** [comment]
> can you paste ([inside a code block, ideally](https://i.witch.gq/YnL28E1z.png)) the error that is logged to the console right before this happens. It'll be right after the words `Failed to download`. I suspect you have a bad URL that is preventing the connection from ever being created.
> 
> I will fix the error that you've given, but it's actually hiding another error that was just caught. So even when I fix it you'll get another error.
I can't currently go and check what the error was, but It seemed like it was trying to download libraries from my website.

**Comment by i-eat-burgers** [comment]
> can you paste ([inside a code block, ideally](https://i.witch.gq/YnL28E1z.png)) the error that is logged to the console right before this happens. It'll be right after the words `Failed to download`. I suspect you have a bad URL that is preventing the connection from ever being created.
> 
> I will fix the error that you've given, but it's actually hiding another error that was just caught. So even when I fix it you'll get another error.

```
[warning] Failed to download http://resources.download.minecraft.net/a1/a11ac56ec61c17e99f4ee33d8712404edf442720
java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at com.skcraft.launcher.util.HttpRequest.runRequest(HttpRequest.java:160)
	at com.skcraft.launcher.util.HttpRequest.execute(HttpRequest.java:118)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:266)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[warning] Failed to download http://resources.download.minecraft.net/68/68e0a58848bbdad12ad2b216d7244754459c9516
java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at com.skcraft.launcher.util.HttpRequest.runRequest(HttpRequest.java:160)
	at com.skcraft.launcher.util.HttpRequest.execute(HttpRequest.java:118)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:266)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info] Downloading C:\Users\Bad\Documents\BadsLauncher\temp\install\07\075b13d7fee49a5f197ca15f1a435834f1fdc3c0 from [http://resources.download.minecraft.net/34/342790fb463baafaa7b8d61102567b48505cbdf2]
[severe] input future failed.
java.lang.IllegalArgumentException: No connection has been made
	at com.skcraft.launcher.util.HttpRequest.getResponseCode(HttpRequest.java:243)
	at com.skcraft.launcher.util.HttpRequest.isSuccessCode(HttpRequest.java:255)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:272)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info] Download of C:\Users\Bad\Documents\BadsLauncher\temp\install\07\075b13d7fee49a5f197ca15f1a435834f1fdc3c0 was interrupted
[warning] Task failed
java.io.IOException: Something went wrong
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:134)
	at com.skcraft.launcher.install.Installer.download(Installer.java:50)
	at com.skcraft.launcher.update.Updater.update(Updater.java:203)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No connection has been made
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:132)
	... 8 more
Caused by: java.lang.IllegalArgumentException: No connection has been made
	at com.skcraft.launcher.util.HttpRequest.getResponseCode(HttpRequest.java:243)
	at com.skcraft.launcher.util.HttpRequest.isSuccessCode(HttpRequest.java:255)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:272)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	... 4 more
```

Here you go!

**Comment by hedgehog1029** [comment]
connection timeouts? is your internet OK

i've pushed commit 5b742bc1a1905ab4275086e0bdb6c391448aa19c which means the error dialog will report the correct error at least. but yeah nothing I can do about connection timeouts, that's a local problem

**Comment by i-eat-burgers** [comment]
> connection timeouts? is your internet OK
> 
> i've pushed commit [5b742bc](https://github.com/SKCraft/Launcher/commit/5b742bc1a1905ab4275086e0bdb6c391448aa19c) which means the error dialog will report the correct error at least. but yeah nothing I can do about connection timeouts, that's a local problem

My internet doesn't have any problems tho, that's quite odd.

**Comment by i-eat-burgers** [comment]
Also the error always happens at the same file/time of installation.

**Comment by hedgehog1029** [comment]
That's maybe not surprising if all the connections are timing out; it'll try and download 6 files at once, but the connection is never established so they just sit and wait for the timeout, and when the connect timeout elapses everything fails at once.

Unique error I have to say. I can connect to `resources.download.minecraft.net` just fine; is it possible there is a proxy or firewall in the way that is blocking connections (for example, at work or school, or on a home connection with a stock router with some kind of filtering)? You could try visiting http://resources.download.minecraft.net/68/68e0a58848bbdad12ad2b216d7244754459c9516 in a browser.

**Comment by i-eat-burgers** [comment]
> That's maybe not surprising if all the connections are timing out; it'll try and download 6 files at once, but the connection is never established so they just sit and wait for the timeout, and when the connect timeout elapses everything fails at once.
> 
> Unique error I have to say. I can connect to `resources.download.minecraft.net` just fine; is it possible there is a proxy or firewall in the way that is blocking connections (for example, at work or school, or on a home connection with a stock router with some kind of filtering)? You could try visiting http://resources.download.minecraft.net/68/68e0a58848bbdad12ad2b216d7244754459c9516 in a browser.

No filtering/blocking and also the file downloads fine when I go to the site....

**Comment by hedgehog1029** [comment]
Do you know what version of Java you're using for the launcher?

**Comment by i-eat-burgers** [comment]
> Do you know what version of Java you're using for the launcher?

8

**Comment by hedgehog1029** [comment]
Closing as stale; likely local firewall/networking issue of some kind.
