### ISSUE TITLE
How to do it on Fabric?

### ISSUE THREAD

**Issue by wojtek4563** [SKCraft/Launcher#426]
I have no idea how to do it on fabric. What files should i put in loaders folder?

**Comment by hedgehog1029** [comment]
Here: https://github.com/SKCraft/Launcher/wiki/Using-Loaders#fabric

**Comment by wojtek4563** [comment]
I tried, but it gives me an error.


java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.17/1.17.json
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:168)
	at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:63)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Probabbly this happens because of new java version in minecraft 1.17, but I don't know so I asked

**Comment by hedgehog1029** [comment]
nah your copy of the launcher is outdated. that URL isn't used anymore

**Comment by wojtek4563** [comment]
now i see that the most recent release is from 2015...
so i should use any of these releases, but just download code?

**Comment by wojtek4563** [comment]
yeah, now it works
thank you
