### ISSUE TITLE
Error reading package manifest. 

### ISSUE THREAD

**Issue by HarrisFauntleroy** [SKCraft/Launcher#429]
I might be stupid but please help.

I can get as far as launching, then it errors out.

On Fedora 34, using Github pages as host.

To report this error, please provide:

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@2924ba33; line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1415)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.asJson(HttpRequest.java:550)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:92)
	at com.skcraft.launcher.update.Updater.update(Updater.java:165)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by hedgehog1029** [comment]
Whatever URL is being accessed for the package manifest is returning HTML, which the JSON parser chokes on. Not sure why, the URL join might be doing something weird

**Comment by hedgehog1029** [comment]
If you search in the launcher log for `setManifestUrl` you should be able to see what URL it's trying to access for the instance

**Comment by HarrisFauntleroy** [comment]
I think ive managed to fix it by appending ?raw=true to the end of the package.json location reference

{
  "minimumVersion" : 1,
  "packages" : [
    {
      "title" : null,
      "name" : "Minecraft with frens",
      "version" : "1",
      "location" : "minecraft-with-frens.json?raw=true",
      "priority" : 0
    }
  ]
}

**Comment by HarrisFauntleroy** [comment]
As I am using github pages,

**Comment by hedgehog1029** [comment]
Slightly wack but if it works, that's a solution!
