### ISSUE TITLE
Invalid hash

### ISSUE THREAD

**Issue by WILLIAM8812** [SKCraft/Launcher#431]
Hello, 
When i try to launch my modpack i get the following error :

```
java.lang.RuntimeException: Artifact 'D:\dev\Launcher-master\launcher\build\libs\libraries\net\minecraft\client\1.16.5-20210115.111550\client-1.16.5-20210115.111550-extra.jar' has invalid hash!
	at com.skcraft.launcher.install.ProcessorTask.execute(ProcessorTask.java:121)
	at com.skcraft.launcher.install.Installer$TaskQueue.execute(Installer.java:109)
	at com.skcraft.launcher.install.Installer.executeLate(Installer.java:61)
	at com.skcraft.launcher.update.Updater.update(Updater.java:209)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

 I've seen it trying to download the file using localhost, maybe a proxy error idk ?
 Thanks

**Comment by hedgehog1029** [comment]
Likely you have mismatched minecraft & forge versions.

**Comment by WILLIAM8812** [comment]
Oh yeah thanks
