### ISSUE TITLE
1.12.2 modpack fail to launxh but builds fine

### ISSUE THREAD

**Issue by darealHeroBrine** [SKCraft/Launcher#432]
The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Im making a 1.12.2 modpack and this happens is skcraft launcher stop working for 1.12.2 and below?? if not can i be told of a fix for this please?

**Comment by hedgehog1029** [comment]
Java version is too new for Forge 1.12; you'll need to change the java path in the settings. Possibly install older Java first

There's an upcoming update to allow per-pack java settings & automatically pick the best setting when appropriate, but it's taking a little while to get right.

**Comment by darealHeroBrine** [comment]
i thought i did get an older one ill try again tho thx for your response.

**Comment by darealHeroBrine** [comment]
The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

i think its still the same error?
