### ISSUE TITLE
SKCraft ERROR CODE 1

### ISSUE THREAD

**Issue by Uteryon** [SKCraft/Launcher#44]
~[forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310) ~[forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:211) ~[forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch[forge-1.7.10-10.13.0.1208.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.0.1208.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11-r1.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11-r1.jar:?]
(FMLLaunchHandler.java:34) java.lang.UnsupportedClassVersionError: nf/fr/ephys/cookiecore/common/CookieCoreASM : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:1.loadCoreMod(CoreModManager.java:381)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:211)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
90)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.relauncher.CoreModManagerProcess ended with code: 1

Please help me I'm using Yosemite 10.10.1 and SKCraft stops processing just before opening Minecraft. The java window is already opening when it's suddenly closed along with "Process ended with code 1"

**Comment by sk89q** [comment]
```java
java.lang.UnsupportedClassVersionError: nf/fr/ephys/cookiecore/common/CookieCoreASM : Unsupported major.minor version 51.0
```

51 = Java 7

Whatever "CookieCore" is requires Java 7 but you are using Java 6.
