### ISSUE TITLE
Failed to download resources

### ISSUE THREAD

**Issue by brunyman** [SKCraft/Launcher#495]
Just download forge-1.19.3-44.1.5-installer.jar and place it in the loaders folder.

On modpack installation it fails to download resources from http://resources.download.minecraft.net , the issue seems to be because it tries to download the resources from http instead of https

How to fix this?

[info] Downloading C:\Users\brunyman\Documents\CraftersLand Launcher\temp\install\9d\9db4f50311541d93bea3b413f83c0fc53819233a from [http://resources.download.minecraft.net/26/2667f5bc36427218608c3fc7b1af48b047ba5b8d]
[warning] Failed to download http://resources.download.minecraft.net/26/2667f5bc36427218608c3fc7b1af48b047ba5b8d
java.io.IOException: Did not get expected response code, got 400 for http://resources.download.minecraft.net/26/2667f5bc36427218608c3fc7b1af48b047ba5b8d
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:211)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.tryDownloadFrom(HttpDownloader.java:266)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:251)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

https://pastebin.com/e3099aQw

**Comment by brunyman** [comment]
It seems I can only download resources from 1.12.2 version, anything older or newer will fail to download resources with that error

**Comment by hedgehog1029** [comment]
Also reported as #486 but yes it's suddenly obvious that it's not upgrading to https - let me have a dig and see where it's getting those URLs from in the first place...

**Comment by hedgehog1029** [comment]
Fixed in 8dfb0490e3e01558fa75e99d707c7849d386b4dc
