### ISSUE TITLE
getting a 403 and not knowing why

### ISSUE THREAD

**Issue by strich3** [SKCraft/Launcher#525]
To report this error, please provide:

java.io.IOException: Did not get expected response code, got 403 for https://api.minecraftservices.com/authentication/login_with_xbox
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:211)
	at com.skcraft.launcher.auth.microsoft.MinecraftServicesAuthorizer.authorizeWithMinecraft(MinecraftServicesAuthorizer.java:24)
	at com.skcraft.launcher.auth.MicrosoftLoginService.performLogin(MicrosoftLoginService.java:99)
	at com.skcraft.launcher.auth.MicrosoftLoginService.login(MicrosoftLoginService.java:58)
	at com.skcraft.launcher.dialog.AccountSelectDialog.lambda$attemptMicrosoftLogin$7(AccountSelectDialog.java:153)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by D3nnis3n** [comment]
Similar here when trying to login with MS account:

java.lang.IllegalArgumentException: No input stream available
	at com.skcraft.launcher.util.HttpRequest.returnContent(HttpRequest.java:308)
	at com.skcraft.launcher.auth.microsoft.XboxTokenAuthorizer.lambda$authorizeWithXbox$1(XboxTokenAuthorizer.java:41)
	at com.skcraft.launcher.util.HttpRequest.expectResponseCodeOr(HttpRequest.java:230)
	at com.skcraft.launcher.auth.microsoft.XboxTokenAuthorizer.authorizeWithXbox(XboxTokenAuthorizer.java:40)
	at com.skcraft.launcher.auth.MicrosoftLoginService.performLogin(MicrosoftLoginService.java:98)
	at com.skcraft.launcher.auth.MicrosoftLoginService.login(MicrosoftLoginService.java:58)
	at com.skcraft.launcher.dialog.AccountSelectDialog.lambda$attemptMicrosoftLogin$7(AccountSelectDialog.java:153)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by StephanWithPH** [comment]
I am getting the exact same error too. For me it works with the default SKCraft client id, so it seems like there is something going wrong with the custom EntraID application. I am still not sure what and why.

**Comment by hedgehog1029** [comment]
> I am getting the exact same error too. For me the launcher works with the default SKCraft client id, so it seems like there is something going wrong with the custom EntraID application. I am still not sure what and why.

Microsoft now requires you to [register app IDs](https://help.minecraft.net/hc/en-us/articles/16254801392141p) if you want to use them for Minecraft auth.
