### ISSUE TITLE
Neoforge really supported?

### ISSUE THREAD

**Issue by oxodao** [SKCraft/Launcher#530]
Hi,

I was wondering if neoforged was really supported ? I've seen this commit https://github.com/SKCraft/Launcher/commit/b5fe175650b14dac472bb84a95d15613078a84c0 but it doesn't look like it works on my end (1.21 though):

```
The game is running. Please wait.
Exception in thread "main" java.lang.module.ResolutionException: Modules org.apache.logging.log4j.slf4j and org.apache.logging.log4j.slf4j2.impl export package org.apache.logging.slf4j to module net.neoforged.mergetool.api
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
Process ended with code: 1
```

I have been using SKCraft for a long time so I don't think I'm doing something wrong though it might still be the case.

I've downloaded NeoForge from [here](https://projects.neoforged.net/neoforged/neoforge) selecting the 1.21.0 version and putting it in loaders as I've always done for Forge.

I'm running Java 21.0.3 since 17 is no longer supported on MC1.21, maybe this is related ?

**Comment by hedgehog1029** [comment]
It's very possible that a new step was added to the Neoforge installer in 1.21 that the launcher doesn't implement yet - I'll have to take a look. That error implies they've started doing some Jigsaw module stuff...

**Comment by znowfox** [comment]
hey mate, is there any current way of building a neoforge (1.21.1) pack ?

**Comment by hedgehog1029** [comment]
Investigating this this evening, finally, and turns out this is related to #533 - fix should be in shortly

**Comment by hedgehog1029** [comment]
Fixed in 950ad3d92a06dccddf7fd8a28c56ee617107844b, I've got a successful launch of Neoforge 1.21.3

**Comment by znowfox** [comment]
nice one
