### ISSUE TITLE
Fabric Loader 1.16.9 on 1.21.3 - Duplicate ASM Error

### ISSUE THREAD

**Issue by andy3471** [SKCraft/Launcher#533]
I've tried creating a new modpack using the modpack creator for version 1.21.3.

If I add faboric-loader-0.16.9 from the Frabic Maven, but make no other changed, I get the following error when launching the modpack:
```The game is running. Please wait.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/D:/MEGA/360NoHope/NoHopeLauncherClient/.modpacks/staging/launcher/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/D:/MEGA/360NoHope/NoHopeLauncherClient/.modpacks/staging/launcher/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
	at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
	... 1 more
Process ended with code: 1
```

It seems to work fine with 0.16.1 though.

It seems to extract two verisons of the ASM library to my .modpacks/staging/launcher/libraries/org/ow2/asm, 9.7.1 and 9.3. If I clear down the .modpack folder, it seems to extract again

Any ideas?

**Comment by hedgehog1029** [comment]
looks like Fabric added this check in 0.16.2: https://github.com/FabricMC/fabric-loader/pull/965

Sounds like the launcher is currently not overwriting game libraries - I think generally it just concats all the library lists together. Will look into this.

**Comment by Blarnix** [comment]
Any fix or update on this?

**Comment by hedgehog1029** [comment]
Fixed in 950ad3d92a06dccddf7fd8a28c56ee617107844b, libraries should now be deduplicated correctly.
