### ISSUE TITLE
Build error: shadowJar

### ISSUE THREAD

**Issue by ablyss** [SKCraft/Launcher#57]
Fresh download, clean build, and it breaks on build.
(I didn't know whether or not I should've put this code into pastebin or something, so apologies in advance)

:launcher-bootstrap:classes
:launcher-bootstrap:jar
:launcher-bootstrap:assemble
:launcher-bootstrap:compileTestJava UP-TO-DATE
:launcher-bootstrap:processTestResources UP-TO-DATE
:launcher-bootstrap:testClasses UP-TO-DATE
:launcher-bootstrap:test UP-TO-DATE
:launcher-bootstrap:check UP-TO-DATE
:launcher-bootstrap:shadowJar
:launcher-bootstrap:build
:launcher-builder:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
:launcher-builder:processResources UP-TO-DATE
:launcher-builder:classes
:launcher-builder:jar
:launcher-builder:assemble
:launcher-builder:compileTestJava UP-TO-DATE
:launcher-builder:processTestResources UP-TO-DATE
:launcher-builder:testClasses UP-TO-DATE
:launcher-builder:test UP-TO-DATE
:launcher-builder:check UP-TO-DATE
:launcher-builder:shadowJar
:launcher-builder:build
:launcher-fancy:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
:launcher-fancy:processResources
:launcher-fancy:classes
:launcher-fancy:jar
:launcher-fancy:assemble
:launcher-fancy:compileTestJava UP-TO-DATE
:launcher-fancy:processTestResources UP-TO-DATE
:launcher-fancy:testClasses UP-TO-DATE
:launcher-fancy:test UP-TO-DATE
:launcher-fancy:check UP-TO-DATE
:launcher-fancy:shadowJar
ex
java.util.zip.ZipException: invalid distance too far back
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
        at org.apache.commons.io.IOUtils$copyLarge.call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.copyArchiveEntry(ShadowCopyAction.groovy:294)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.this$2$copyArchiveEntry(ShadowCopyAction.groovy)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction$this$2$copyArchiveEntry$5.callCurrent(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.visitArchiveFile(ShadowCopyAction.groovy:225)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.this$2$visitArchiveFile(ShadowCopyAction.groovy)
        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:368)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(Po
goMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(Abs
tractCallSite.java:145)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$_St
reamAction_processArchive_closure3.doCall(ShadowCopyAction.groovy:206)
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1372)
        at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMetho
dSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMeta
MethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
llSite.java:116)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.processArchive(ShadowCopyAction.groovy:204)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.this$2$processArchive(ShadowCopyAction.groovy)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction$this$2$processArchive$4.callCurrent(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.visitFile(ShadowCopyAction.groovy:190)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.this$2$visitFile(ShadowCopyAction.groovy)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction$this$2$visitFile$1.callCurrent(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$Str
eamAction.processFile(ShadowCopyAction.groovy:151)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1$1.
processFile(NormalizingCopyActionDecorator.java:65)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorato
r$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:60)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(Cop
yFileVisitorImpl.java:60)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyF
ileVisitorImpl.java:44)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTree$1.visi
tFile(AbstractFileTree.java:145)
        at org.gradle.api.internal.file.collections.SingletonFileTree.visit(Sing
letonFileTree.java:43)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTr
eeAdapter.java:96)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTree.visit(
AbstractFileTree.java:136)
        at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTre
e.java:54)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpec
ActionImpl.java:37)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpec
ActionImpl.java:24)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecReso
lver.walk(DefaultCopySpec.java:498)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecReso
lver.walk(DefaultCopySpec.java:500)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpe
c.java:322)
        at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingS
tream.process(CopySpecBackedCopyActionProcessingStream.java:36)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorato
r$1.process(DuplicateHandlingCopyActionDecorator.java:44)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.pr
ocess(NormalizingCopyActionDecorator.java:56)
        at org.gradle.api.internal.file.copy.CopyActionProcessingStream$process.
call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$1.e
xecute(ShadowCopyAction.groovy:78)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$1$e
xecute.call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.wit
hResource(ShadowCopyAction.groovy:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaM
ethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(
StaticMetaMethodSite.java:99)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(Abst
ractCallSite.java:169)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.exe
cute(ShadowCopyAction.groovy:75)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.exec
ute(NormalizingCopyActionDecorator.java:52)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorato
r.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActi
onExecuter.java:38)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:83)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.copy(Shado
wJar.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
e(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
ter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
:launcher-fancy:shadowJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher-fancy:shadowJar'.
> java.util.zip.ZipException: invalid distance too far back

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 10.599 secs

D:\Launcher-master2\Launcher-master>

For the record, this didn't happen two nights ago in the same scenario.

**Comment by sk89q** [comment]
Not quite sure.

Update your Java version?
Your hard drive isn't failing, right?

**Comment by ablyss** [comment]
@sk89q fixed it. It was .gradle that was in my user folder. Deleting and letting gradlew redownload it resolved the problem.
