### ISSUE TITLE
Error on building modpack. Seems to occur on the first mod that uses a custom url with a .url.txt file.

### ISSUE THREAD

**Issue by elitefroggy** [SKCraft/Launcher#75]
[info] Adding mods/1.7.10/Baubles-1.7.10-1.0.1.10.jar from C:\Files\modpack\pack
\TPPI2\.\src\mods\1.7.10\Baubles-1.7.10-1.0.1.10.jar...
Exception in thread "main" java.io.FileNotFoundException: upload\objects\http:\a
ddons-origin.cursecdn.com\files\2224\857\Baubles-1.7.10-1.0.1.10.jar (The filena
me, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.common.io.Files$FileByteSink.openStream(Files.java:245)
        at com.google.common.io.Files$FileByteSink.openStream(Files.java:233)
        at com.google.common.io.ByteSource.copyTo(ByteSource.java:248)
        at com.google.common.io.Files.copy(Files.java:458)
        at com.skcraft.launcher.builder.ClientFileCollector.onFile(ClientFileCol
lector.java:82)
        at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.jav
a:73)
        at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.jav
a:68)
        at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.jav
a:68)
        at com.skcraft.launcher.builder.DirectoryWalker.walk(DirectoryWalker.jav
a:43)
        at com.skcraft.launcher.builder.PackageBuilder.addFiles(PackageBuilder.j
ava:114)
        at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:
392)

Am I doing something wrong here? i have a Baubles-1.7.10-1.0.1.10.jar.url.txt file next to my Baubles-1.7.10-1.0.1.10.jar file, with this in it : 
http://addons-origin.cursecdn.com/files/2224/857/Baubles-1.7.10-1.0.1.10.jar

**Comment by sk89q** [comment]
Fixed
